// frontend/src/components/budgets/budget-form-dialog.tsx
'use client';

import { zodResolver } from '@hookform/resolvers/zod';
import { useForm } from 'react-hook-form';
import { toast } from 'sonner';
import { Button } from '@/components/ui/button';
import {
  Dialog,
  DialogContent,
  DialogFooter,
  DialogHeader,
  DialogTitle,
} from '@/components/ui/dialog';
import { Form, FormControl, FormField, FormItem, FormLabel, FormMessage } from '@/components/ui/form';
import { Input } from '@/components/ui/input';
import { Select, SelectContent, SelectItem, SelectTrigger, SelectValue } from '@/components/ui/select';
import { getApiErrorMessage } from '@/lib/api/client';
import { useCreateBudget } from '@/lib/hooks/use-budgets';
import { useCategories } from '@/lib/hooks/use-categories';
import { TransactionType } from '@/lib/types';
import { budgetSchema, type BudgetFormValues } from '@/lib/validations/budget';

export function BudgetFormDialog({
  householdId,
  open,
  onOpenChange,
}: {
  householdId: string;
  open: boolean;
  onOpenChange: (open: boolean) => void;
}) {
  const createBudget = useCreateBudget(householdId);
  const { data: categories } = useCategories(householdId, TransactionType.EXPENSE);
  const now = new Date();

  const form = useForm<BudgetFormValues>({
    resolver: zodResolver(budgetSchema),
    defaultValues: {
      categoryId: '',
      month: now.getMonth() + 1,
      year: now.getFullYear(),
      limitAmount: 0,
      alertThreshold: 80,
    },
  });

  const onSubmit = (values: BudgetFormValues) => {
    createBudget.mutate(values, {
      onSuccess: () => {
        toast.success('Orçamento criado');
        form.reset();
        onOpenChange(false);
      },
      onError: (error) => toast.error(getApiErrorMessage(error)),
    });
  };

  return (
    <Dialog open={open} onOpenChange={onOpenChange}>
      <DialogContent>
        <DialogHeader>
          <DialogTitle>Novo orçamento</DialogTitle>
        </DialogHeader>
        <Form {...form}>
          <form onSubmit={form.handleSubmit(onSubmit)} className="space-y-4">
            <FormField
              control={form.control}
              name="categoryId"
              render={({ field }) => (
                <FormItem>
                  <FormLabel>Categoria</FormLabel>
                  <Select value={field.value} onValueChange={field.onChange}>
                    <FormControl>
                      <SelectTrigger>
                        <SelectValue placeholder="Selecione uma categoria" />
                      </SelectTrigger>
                    </FormControl>
                    <SelectContent>
                      {categories?.map((category) => (
                        <SelectItem key={category.id} value={category.id}>
                          {category.name}
                        </SelectItem>
                      ))}
                    </SelectContent>
                  </Select>
                  <FormMessage />
                </FormItem>
              )}
            />
            <div className="grid grid-cols-2 gap-4">
              <FormField
                control={form.control}
                name="month"
                render={({ field }) => (
                  <FormItem>
                    <FormLabel>Mês</FormLabel>
                    <FormControl>
                      <Input type="number" min="1" max="12" {...field} />
                    </FormControl>
                    <FormMessage />
                  </FormItem>
                )}
              />
              <FormField
                control={form.control}
                name="year"
                render={({ field }) => (
                  <FormItem>
                    <FormLabel>Ano</FormLabel>
                    <FormControl>
                      <Input type="number" min="2000" {...field} />
                    </FormControl>
                    <FormMessage />
                  </FormItem>
                )}
              />
            </div>
            <FormField
              control={form.control}
              name="limitAmount"
              render={({ field }) => (
                <FormItem>
                  <FormLabel>Limite mensal</FormLabel>
                  <FormControl>
                    <Input type="number" step="0.01" min="0" {...field} />
                  </FormControl>
                  <FormMessage />
                </FormItem>
              )}
            />
            <DialogFooter>
              <Button type="submit" disabled={createBudget.isPending}>
                {createBudget.isPending ? 'Salvando...' : 'Criar orçamento'}
              </Button>
            </DialogFooter>
          </form>
        </Form>
      </DialogContent>
    </Dialog>
  );
}

// frontend-vue/src/components/budgets/BudgetFormDialog.vue
<script setup lang="ts">
import { toTypedSchema } from '@vee-validate/zod';
import { useForm } from 'vee-validate';
import { toast } from 'vue-sonner';
import Button from '@/components/ui/Button.vue';
import { Dialog, DialogContent, DialogFooter, DialogHeader, DialogTitle } from '@/components/ui/dialog';
import FormItem from '@/components/ui/FormItem.vue';
import FormMessage from '@/components/ui/FormMessage.vue';
import Input from '@/components/ui/Input.vue';
import Label from '@/components/ui/Label.vue';
import { Select, SelectContent, SelectItem, SelectTrigger, SelectValue } from '@/components/ui/select';
import { getApiErrorMessage } from '@/lib/api/client';
import { useCreateBudget } from '@/composables/useBudgets';
import { useCategories } from '@/composables/useCategories';
import { TransactionType } from '@/lib/types';
import { budgetSchema } from '@/lib/validations/budget';

const props = defineProps<{ householdId: string }>();
const open = defineModel<boolean>('open', { required: true });

const createBudget = useCreateBudget(props.householdId);
const { data: categories } = useCategories(props.householdId, TransactionType.EXPENSE);
const now = new Date();

const { defineField, errors, handleSubmit, resetForm } = useForm({
  validationSchema: toTypedSchema(budgetSchema),
  initialValues: {
    categoryId: '',
    month: now.getMonth() + 1,
    year: now.getFullYear(),
    limitAmount: 0,
    alertThreshold: 80,
  },
});

const [categoryId, categoryIdAttrs] = defineField('categoryId');
const [month, monthAttrs] = defineField('month');
const [year, yearAttrs] = defineField('year');
const [limitAmount, limitAmountAttrs] = defineField('limitAmount');

const onSubmit = handleSubmit((values) => {
  createBudget.mutate(values, {
    onSuccess: () => {
      toast.success('Orçamento criado');
      resetForm();
      open.value = false;
    },
    onError: (error) => toast.error(getApiErrorMessage(error)),
  });
});
</script>

<template>
  <Dialog v-model:open="open">
    <DialogContent>
      <DialogHeader>
        <DialogTitle>Novo orçamento</DialogTitle>
      </DialogHeader>
      <form class="space-y-4" @submit="onSubmit">
        <FormItem>
          <Label>Categoria</Label>
          <Select v-model="categoryId" v-bind="categoryIdAttrs">
            <SelectTrigger>
              <SelectValue placeholder="Selecione uma categoria" />
            </SelectTrigger>
            <SelectContent>
              <SelectItem v-for="category in categories" :key="category.id" :value="category.id">
                {{ category.name }}
              </SelectItem>
            </SelectContent>
          </Select>
          <FormMessage :message="errors.categoryId" />
        </FormItem>
        <div class="grid grid-cols-2 gap-4">
          <FormItem>
            <Label for="month">Mês</Label>
            <Input id="month" v-model="month" v-bind="monthAttrs" type="number" min="1" max="12" />
            <FormMessage :message="errors.month" />
          </FormItem>
          <FormItem>
            <Label for="year">Ano</Label>
            <Input id="year" v-model="year" v-bind="yearAttrs" type="number" min="2000" />
            <FormMessage :message="errors.year" />
          </FormItem>
        </div>
        <FormItem>
          <Label for="limitAmount">Limite mensal</Label>
          <Input id="limitAmount" v-model="limitAmount" v-bind="limitAmountAttrs" type="number" step="0.01" min="0" />
          <FormMessage :message="errors.limitAmount" />
        </FormItem>
        <DialogFooter>
          <Button type="submit" :disabled="createBudget.isPending.value">
            {{ createBudget.isPending.value ? 'Salvando...' : 'Criar orçamento' }}
          </Button>
        </DialogFooter>
      </form>
    </DialogContent>
  </Dialog>
</template>
