// frontend/src/components/layout/app-header.tsx
'use client';

import * as React from 'react';
import { Menu, Wallet2 } from 'lucide-react';
import { Button } from '@/components/ui/button';
import { Sheet, SheetContent, SheetHeader, SheetTitle, SheetTrigger } from '@/components/ui/sheet';
import { HouseholdSwitcher } from '@/components/layout/household-switcher';
import { NavLinks } from '@/components/layout/nav-links';
import { NotificationBell } from '@/components/layout/notification-bell';
import { ThemeToggle } from '@/components/layout/theme-toggle';
import { UserNav } from '@/components/layout/user-nav';

export function AppHeader() {
  const [open, setOpen] = React.useState(false);

  return (
    <header className="sticky top-0 z-40 flex h-16 items-center gap-3 border-b-2 border-border bg-background px-4">
      <Sheet open={open} onOpenChange={setOpen}>
        <SheetTrigger asChild>
          <Button variant="ghost" size="icon" className="lg:hidden">
            <Menu className="h-5 w-5" />
          </Button>
        </SheetTrigger>
        <SheetContent side="left" className="w-64">
          <SheetHeader>
            <SheetTitle className="flex items-center gap-2">
              <Wallet2 className="h-5 w-5 text-primary" />
              Together Account
            </SheetTitle>
          </SheetHeader>
          <div className="mt-6">
            <NavLinks onNavigate={() => setOpen(false)} />
          </div>
        </SheetContent>
      </Sheet>

      <div className="hidden items-center gap-2 font-extrabold lg:flex">
        <Wallet2 className="h-5 w-5 text-primary" />
        <span>Together Account</span>
      </div>

      <div className="flex-1">
        <HouseholdSwitcher />
      </div>

      <div className="flex items-center gap-1">
        <NotificationBell />
        <ThemeToggle />
        <UserNav />
      </div>
    </header>
  );
}

// frontend/src/components/layout/AppHeader.vue
<script setup lang="ts">
import { ref } from 'vue';
import { Menu, Wallet2 } from '@lucide/vue';
import Button from '@/components/ui/Button.vue';
import { Sheet, SheetContent, SheetHeader, SheetTitle, SheetTrigger } from '@/components/ui/sheet';
import HouseholdSwitcher from '@/components/layout/HouseholdSwitcher.vue';
import NavLinks from '@/components/layout/NavLinks.vue';
import NotificationBell from '@/components/layout/NotificationBell.vue';
import ThemeToggle from '@/components/layout/ThemeToggle.vue';
import UserNav from '@/components/layout/UserNav.vue';

const open = ref(false);
</script>

<template>
  <header class="sticky top-0 z-40 flex h-16 items-center gap-3 border-b-2 border-border bg-background px-4">
    <Sheet v-model:open="open">
      <SheetTrigger as-child>
        <Button variant="ghost" size="icon" class="lg:hidden">
          <Menu class="h-5 w-5" />
        </Button>
      </SheetTrigger>
      <SheetContent side="left" class="w-64">
        <SheetHeader>
          <SheetTitle class="flex items-center gap-2">
            <Wallet2 class="h-5 w-5 text-primary" />
            Together Account
          </SheetTitle>
        </SheetHeader>
        <div class="mt-6">
          <NavLinks :on-navigate="() => (open = false)" />
        </div>
      </SheetContent>
    </Sheet>

    <div class="hidden items-center gap-2 font-extrabold lg:flex">
      <Wallet2 class="h-5 w-5 text-primary" />
      <span>Together Account</span>
    </div>

    <div class="flex-1">
      <HouseholdSwitcher />
    </div>

    <div class="flex items-center gap-1">
      <NotificationBell />
      <ThemeToggle />
      <UserNav />
    </div>
  </header>
</template>
