// frontend/src/components/layout/EmptyState.vue
<script setup lang="ts">
import type { Component } from 'vue';

defineProps<{ icon: Component; title: string; description?: string }>();
</script>

<template>
  <div class="flex flex-col items-center justify-center gap-3 rounded-lg border-2 border-dashed border-border p-10 text-center">
    <component :is="icon" class="h-8 w-8 text-muted-foreground" />
    <div>
      <p class="font-bold">{{ title }}</p>
      <p v-if="description" class="text-sm font-medium text-muted-foreground">{{ description }}</p>
    </div>
    <slot name="action" />
  </div>
</template>

// frontend/src/components/layout/empty-state.tsx
import type { LucideIcon } from 'lucide-react';

export function EmptyState({
  icon: Icon,
  title,
  description,
  action,
}: {
  icon: LucideIcon;
  title: string;
  description?: string;
  action?: React.ReactNode;
}) {
  return (
    <div className="flex flex-col items-center justify-center gap-3 rounded-lg border-2 border-dashed border-border p-10 text-center">
      <Icon className="h-8 w-8 text-muted-foreground" />
      <div>
        <p className="font-bold">{title}</p>
        {description && <p className="text-sm font-medium text-muted-foreground">{description}</p>}
      </div>
      {action}
    </div>
  );
}
