// frontend/src/components/layout/NavLinks.vue
<script setup lang="ts">
import { RouterLink, useRoute } from 'vue-router';
import { cn } from '@/lib/utils';
import { navItems } from './nav-items';

defineProps<{ onNavigate?: () => void }>();

const route = useRoute();
</script>

<template>
  <nav class="flex flex-col gap-1">
    <RouterLink
      v-for="item in navItems"
      :key="item.href"
      :to="item.href"
      :class="
        cn(
          'flex items-center gap-3 rounded-md border-2 px-3 py-2 text-sm font-bold transition-all',
          route.path.startsWith(item.href)
            ? 'border-border bg-primary text-primary-foreground shadow-brutal-sm'
            : 'border-transparent text-muted-foreground hover:border-border hover:bg-accent hover:text-accent-foreground',
        )
      "
      @click="onNavigate?.()"
    >
      <component :is="item.icon" class="h-4 w-4" />
      {{ item.title }}
    </RouterLink>
  </nav>
</template>

// frontend/src/components/layout/nav-links.tsx
'use client';

import Link from 'next/link';
import { usePathname } from 'next/navigation';
import { cn } from '@/lib/utils';
import { navItems } from './nav-items';

export function NavLinks({ onNavigate }: { onNavigate?: () => void }) {
  const pathname = usePathname();

  return (
    <nav className="flex flex-col gap-1">
      {navItems.map((item) => {
        const isActive = pathname?.startsWith(item.href);
        const Icon = item.icon;
        return (
          <Link
            key={item.href}
            href={item.href}
            onClick={onNavigate}
            className={cn(
              'flex items-center gap-3 rounded-md border-2 px-3 py-2 text-sm font-bold transition-all',
              isActive
                ? 'border-border bg-primary text-primary-foreground shadow-brutal-sm'
                : 'border-transparent text-muted-foreground hover:border-border hover:bg-accent hover:text-accent-foreground',
            )}
          >
            <Icon className="h-4 w-4" />
            {item.title}
          </Link>
        );
      })}
    </nav>
  );
}
