// frontend-vue/src/components/dashboard/CategoryBreakdownChart.vue
<script setup lang="ts">
import { computed } from 'vue';
import { Doughnut } from 'vue-chartjs';
import type { ChartData, ChartOptions } from 'chart.js';
import { PieChart as PieChartIcon } from '@lucide/vue';
import { Card, CardContent, CardHeader, CardTitle } from '@/components/ui/card';
import EmptyState from '@/components/layout/EmptyState.vue';
import { chartChrome, getCategoricalColor } from '@/lib/chart-colors';
import { useChartMode } from '@/composables/useChartMode';
import type { CategoryBreakdown } from '@/lib/types';
import { formatCurrency } from '@/lib/utils';

const MAX_SLICES = 7;

const props = defineProps<{ data: CategoryBreakdown[] }>();

const mode = useChartMode();

const chartEntries = computed(() => {
  const sorted = [...props.data].sort((a, b) => b.total - a.total);
  const top = sorted.slice(0, MAX_SLICES);
  const rest = sorted.slice(MAX_SLICES);
  const restTotal = rest.reduce((sum, item) => sum + item.total, 0);
  return restTotal > 0
    ? [...top, { categoryId: 'other', name: 'Outros', color: '', total: restTotal }]
    : top;
});

const chartData = computed<ChartData<'doughnut'>>(() => ({
  labels: chartEntries.value.map((entry) => entry.name),
  datasets: [
    {
      data: chartEntries.value.map((entry) => entry.total),
      backgroundColor: chartEntries.value.map((_, index) => getCategoricalColor(index, mode.value)),
      borderColor: chartChrome[mode.value].primaryInk,
      borderWidth: 3,
    },
  ],
}));

const chartOptions = computed<ChartOptions<'doughnut'>>(() => {
  const chrome = chartChrome[mode.value];
  return {
    responsive: true,
    maintainAspectRatio: false,
    cutout: '55%',
    plugins: {
      legend: {
        position: 'bottom',
        labels: { color: chrome.secondaryInk, font: { size: 12 } },
      },
      tooltip: {
        backgroundColor: chrome.surface,
        titleColor: chrome.primaryInk,
        bodyColor: chrome.primaryInk,
        borderColor: chrome.primaryInk,
        borderWidth: 2,
        callbacks: {
          label: (context) => `${context.label}: ${formatCurrency(Number(context.raw))}`,
        },
      },
    },
  };
});
</script>

<template>
  <Card>
    <CardHeader>
      <CardTitle class="text-base">Despesas por categoria</CardTitle>
    </CardHeader>
    <CardContent v-if="!data.length">
      <EmptyState :icon="PieChartIcon" title="Sem despesas neste período" />
    </CardContent>
    <CardContent v-else class="h-80">
      <Doughnut :data="chartData" :options="chartOptions" />
    </CardContent>
  </Card>
</template>

// frontend/src/components/dashboard/category-breakdown-chart.tsx
'use client';

import { Cell, Legend, Pie, PieChart, ResponsiveContainer, Tooltip } from 'recharts';
import { Card, CardContent, CardHeader, CardTitle } from '@/components/ui/card';
import { EmptyState } from '@/components/layout/empty-state';
import { chartChrome, getCategoricalColor } from '@/lib/chart-colors';
import { useChartMode } from '@/lib/hooks/use-chart-mode';
import type { CategoryBreakdown } from '@/lib/types';
import { formatCurrency } from '@/lib/utils';
import { PieChart as PieChartIcon } from 'lucide-react';

const MAX_SLICES = 7;

export function CategoryBreakdownChart({ data }: { data: CategoryBreakdown[] }) {
  const mode = useChartMode();
  const chrome = chartChrome[mode];

  if (!data.length) {
    return (
      <Card>
        <CardHeader>
          <CardTitle className="text-base">Despesas por categoria</CardTitle>
        </CardHeader>
        <CardContent>
          <EmptyState icon={PieChartIcon} title="Sem despesas neste período" />
        </CardContent>
      </Card>
    );
  }

  const sorted = [...data].sort((a, b) => b.total - a.total);
  const top = sorted.slice(0, MAX_SLICES);
  const rest = sorted.slice(MAX_SLICES);
  const restTotal = rest.reduce((sum, item) => sum + item.total, 0);
  const chartData = restTotal > 0 ? [...top, { categoryId: 'other', name: 'Outros', color: '', total: restTotal }] : top;

  return (
    <Card>
      <CardHeader>
        <CardTitle className="text-base">Despesas por categoria</CardTitle>
      </CardHeader>
      <CardContent className="h-80">
        <ResponsiveContainer width="100%" height="100%">
          <PieChart margin={{ bottom: 24 }}>
            <Pie
              data={chartData}
              dataKey="total"
              nameKey="name"
              cx="50%"
              cy="45%"
              innerRadius={60}
              outerRadius={90}
              paddingAngle={2}
              stroke={chrome.surface}
              strokeWidth={2}
            >
              {chartData.map((entry, index) => (
                <Cell key={entry.categoryId} fill={getCategoricalColor(index, mode)} />
              ))}
            </Pie>
            <Tooltip
              contentStyle={{
                background: chrome.surface,
                border: `1px solid ${chrome.gridline}`,
                borderRadius: 8,
                fontSize: 12,
                color: chrome.primaryInk,
              }}
              formatter={(value: number, name) => [formatCurrency(value), name]}
            />
            <Legend
              layout="horizontal"
              verticalAlign="bottom"
              align="center"
              wrapperStyle={{ fontSize: 12, color: chrome.secondaryInk }}
            />
          </PieChart>
        </ResponsiveContainer>
      </CardContent>
    </Card>
  );
}
