// frontend/src/components/dashboard/StatCard.vue
<script setup lang="ts">
import type { Component } from 'vue';
import { Card, CardContent } from '@/components/ui/card';
import { cn } from '@/lib/utils';

withDefaults(
  defineProps<{
    title: string;
    value: string;
    icon: Component;
    tone?: 'default' | 'success' | 'destructive';
  }>(),
  { tone: 'default' },
);
</script>

<template>
  <Card>
    <CardContent class="flex items-center justify-between p-5">
      <div class="space-y-1">
        <p class="text-sm font-bold text-muted-foreground">{{ title }}</p>
        <p
          :class="
            cn(
              'text-2xl font-extrabold tabular-nums',
              tone === 'success' && 'text-success',
              tone === 'destructive' && 'text-destructive',
            )
          "
        >
          {{ value }}
        </p>
      </div>
      <div class="flex h-11 w-11 items-center justify-center rounded-full border-2 border-border bg-accent text-accent-foreground">
        <component :is="icon" class="h-5 w-5" />
      </div>
    </CardContent>
  </Card>
</template>

// frontend/src/components/dashboard/stat-card.tsx
import type { LucideIcon } from 'lucide-react';
import { Card, CardContent } from '@/components/ui/card';
import { cn } from '@/lib/utils';

export function StatCard({
  title,
  value,
  icon: Icon,
  tone = 'default',
}: {
  title: string;
  value: string;
  icon: LucideIcon;
  tone?: 'default' | 'success' | 'destructive';
}) {
  return (
    <Card>
      <CardContent className="flex items-center justify-between p-5">
        <div className="space-y-1">
          <p className="text-sm font-bold text-muted-foreground">{title}</p>
          <p
            className={cn(
              'text-2xl font-extrabold tabular-nums',
              tone === 'success' && 'text-success',
              tone === 'destructive' && 'text-destructive',
            )}
          >
            {value}
          </p>
        </div>
        <div className="flex h-11 w-11 items-center justify-center rounded-full border-2 border-border bg-accent text-accent-foreground">
          <Icon className="h-5 w-5" />
        </div>
      </CardContent>
    </Card>
  );
}
