// frontend/src/components/dashboard/recent-transactions.tsx
import Link from 'next/link';
import { ArrowDownLeft, ArrowUpRight, Receipt } from 'lucide-react';
import { Card, CardContent, CardHeader, CardTitle } from '@/components/ui/card';
import { EmptyState } from '@/components/layout/empty-state';
import { TransactionType, type Transaction } from '@/lib/types';
import { cn, formatCurrency, formatDate } from '@/lib/utils';

export function RecentTransactions({ transactions }: { transactions: Transaction[] }) {
  return (
    <Card>
      <CardHeader className="flex flex-row items-center justify-between">
        <CardTitle className="text-base">Últimas transações</CardTitle>
        <Link href="/transactions" className="text-xs font-medium text-primary hover:underline">
          Ver todas
        </Link>
      </CardHeader>
      <CardContent>
        {transactions.length === 0 ? (
          <EmptyState icon={Receipt} title="Nenhuma transação ainda" />
        ) : (
          <ul className="divide-y">
            {transactions.map((transaction) => {
              const isIncome = transaction.type === TransactionType.INCOME;
              return (
                <li key={transaction.id} className="flex items-center justify-between py-3">
                  <div className="flex items-center gap-3">
                    <div
                      className={cn(
                        'flex h-9 w-9 items-center justify-center rounded-full border-2 border-border',
                        isIncome ? 'bg-success/30 text-success-foreground' : 'bg-destructive/30 text-destructive-foreground',
                      )}
                    >
                      {isIncome ? <ArrowUpRight className="h-4 w-4" /> : <ArrowDownLeft className="h-4 w-4" />}
                    </div>
                    <div>
                      <p className="text-sm font-medium">{transaction.description}</p>
                      <p className="text-xs text-muted-foreground">
                        {transaction.category?.name} • {formatDate(transaction.date)}
                      </p>
                    </div>
                  </div>
                  <span
                    className={cn(
                      'text-sm font-semibold tabular-nums',
                      isIncome ? 'text-success' : 'text-destructive',
                    )}
                  >
                    {isIncome ? '+' : '-'}
                    {formatCurrency(transaction.amount)}
                  </span>
                </li>
              );
            })}
          </ul>
        )}
      </CardContent>
    </Card>
  );
}

// frontend-vue/src/components/dashboard/RecentTransactions.vue
<script setup lang="ts">
import { RouterLink } from 'vue-router';
import { ArrowDownLeft, ArrowUpRight, Receipt } from '@lucide/vue';
import { Card, CardContent, CardHeader, CardTitle } from '@/components/ui/card';
import EmptyState from '@/components/layout/EmptyState.vue';
import { TransactionType, type Transaction } from '@/lib/types';
import { cn, formatCurrency, formatDate } from '@/lib/utils';

defineProps<{ transactions: Transaction[] }>();
</script>

<template>
  <Card>
    <CardHeader class="flex flex-row items-center justify-between">
      <CardTitle class="text-base">Últimas transações</CardTitle>
      <RouterLink to="/transactions" class="text-xs font-medium text-primary hover:underline">
        Ver todas
      </RouterLink>
    </CardHeader>
    <CardContent>
      <EmptyState v-if="transactions.length === 0" :icon="Receipt" title="Nenhuma transação ainda" />
      <ul v-else class="divide-y">
        <li
          v-for="transaction in transactions"
          :key="transaction.id"
          class="flex items-center justify-between py-3"
        >
          <div class="flex items-center gap-3">
            <div
              :class="
                cn(
                  'flex h-9 w-9 items-center justify-center rounded-full border-2 border-border',
                  transaction.type === TransactionType.INCOME
                    ? 'bg-success/30 text-success-foreground'
                    : 'bg-destructive/30 text-destructive-foreground',
                )
              "
            >
              <ArrowUpRight v-if="transaction.type === TransactionType.INCOME" class="h-4 w-4" />
              <ArrowDownLeft v-else class="h-4 w-4" />
            </div>
            <div>
              <p class="text-sm font-medium">{{ transaction.description }}</p>
              <p class="text-xs text-muted-foreground">
                {{ transaction.category?.name }} • {{ formatDate(transaction.date) }}
              </p>
            </div>
          </div>
          <span
            :class="
              cn(
                'text-sm font-semibold tabular-nums',
                transaction.type === TransactionType.INCOME ? 'text-success' : 'text-destructive',
              )
            "
          >
            {{ transaction.type === TransactionType.INCOME ? '+' : '-' }}{{ formatCurrency(transaction.amount) }}
          </span>
        </li>
      </ul>
    </CardContent>
  </Card>
</template>
