// frontend/src/components/goals/contribution-dialog.tsx
'use client';

import { zodResolver } from '@hookform/resolvers/zod';
import { useForm } from 'react-hook-form';
import { toast } from 'sonner';
import { Button } from '@/components/ui/button';
import {
  Dialog,
  DialogContent,
  DialogFooter,
  DialogHeader,
  DialogTitle,
} from '@/components/ui/dialog';
import { Form, FormControl, FormField, FormItem, FormLabel, FormMessage } from '@/components/ui/form';
import { Input } from '@/components/ui/input';
import { getApiErrorMessage } from '@/lib/api/client';
import { useAddContribution } from '@/lib/hooks/use-goals';
import { contributionSchema, type ContributionFormValues } from '@/lib/validations/goal';

export function ContributionDialog({
  householdId,
  goalId,
  open,
  onOpenChange,
}: {
  householdId: string;
  goalId: string | null;
  open: boolean;
  onOpenChange: (open: boolean) => void;
}) {
  const addContribution = useAddContribution(householdId);
  const form = useForm<ContributionFormValues>({
    resolver: zodResolver(contributionSchema),
    defaultValues: { amount: 0, date: new Date().toISOString().slice(0, 10), note: '' },
  });

  const onSubmit = (values: ContributionFormValues) => {
    if (!goalId) return;
    addContribution.mutate(
      { id: goalId, payload: values },
      {
        onSuccess: () => {
          toast.success('Contribuição adicionada');
          form.reset();
          onOpenChange(false);
        },
        onError: (error) => toast.error(getApiErrorMessage(error)),
      },
    );
  };

  return (
    <Dialog open={open} onOpenChange={onOpenChange}>
      <DialogContent>
        <DialogHeader>
          <DialogTitle>Adicionar contribuição</DialogTitle>
        </DialogHeader>
        <Form {...form}>
          <form onSubmit={form.handleSubmit(onSubmit)} className="space-y-4">
            <FormField
              control={form.control}
              name="amount"
              render={({ field }) => (
                <FormItem>
                  <FormLabel>Valor</FormLabel>
                  <FormControl>
                    <Input type="number" step="0.01" min="0" {...field} />
                  </FormControl>
                  <FormMessage />
                </FormItem>
              )}
            />
            <FormField
              control={form.control}
              name="date"
              render={({ field }) => (
                <FormItem>
                  <FormLabel>Data</FormLabel>
                  <FormControl>
                    <Input type="date" {...field} />
                  </FormControl>
                  <FormMessage />
                </FormItem>
              )}
            />
            <DialogFooter>
              <Button type="submit" disabled={addContribution.isPending}>
                {addContribution.isPending ? 'Salvando...' : 'Adicionar'}
              </Button>
            </DialogFooter>
          </form>
        </Form>
      </DialogContent>
    </Dialog>
  );
}

// frontend/src/components/goals/ContributionDialog.vue
<script setup lang="ts">
import { toTypedSchema } from '@vee-validate/zod';
import { useForm } from 'vee-validate';
import { toast } from 'vue-sonner';
import Button from '@/components/ui/Button.vue';
import { Dialog, DialogContent, DialogFooter, DialogHeader, DialogTitle } from '@/components/ui/dialog';
import FormItem from '@/components/ui/FormItem.vue';
import FormMessage from '@/components/ui/FormMessage.vue';
import Input from '@/components/ui/Input.vue';
import Label from '@/components/ui/Label.vue';
import { getApiErrorMessage } from '@/lib/api/client';
import { useAddContribution } from '@/composables/useGoals';
import { contributionSchema } from '@/lib/validations/goal';

const props = defineProps<{ householdId: string; goalId: string | null }>();
const open = defineModel<boolean>('open', { required: true });

const addContribution = useAddContribution(props.householdId);
const { defineField, errors, handleSubmit, resetForm } = useForm({
  validationSchema: toTypedSchema(contributionSchema),
  initialValues: { amount: 0, date: new Date().toISOString().slice(0, 10), note: '' },
});

const [amount, amountAttrs] = defineField('amount');
const [date, dateAttrs] = defineField('date');

const onSubmit = handleSubmit((values) => {
  if (!props.goalId) return;
  addContribution.mutate(
    { id: props.goalId, payload: values },
    {
      onSuccess: () => {
        toast.success('Contribuição adicionada');
        resetForm();
        open.value = false;
      },
      onError: (error) => toast.error(getApiErrorMessage(error)),
    },
  );
});
</script>

<template>
  <Dialog v-model:open="open">
    <DialogContent>
      <DialogHeader>
        <DialogTitle>Adicionar contribuição</DialogTitle>
      </DialogHeader>
      <form class="space-y-4" @submit="onSubmit">
        <FormItem>
          <Label for="amount">Valor</Label>
          <Input id="amount" v-model="amount" v-bind="amountAttrs" type="number" step="0.01" min="0" />
          <FormMessage :message="errors.amount" />
        </FormItem>
        <FormItem>
          <Label for="date">Data</Label>
          <Input id="date" v-model="date" v-bind="dateAttrs" type="date" />
          <FormMessage :message="errors.date" />
        </FormItem>
        <DialogFooter>
          <Button type="submit" :disabled="addContribution.isPending.value">
            {{ addContribution.isPending.value ? 'Salvando...' : 'Adicionar' }}
          </Button>
        </DialogFooter>
      </form>
    </DialogContent>
  </Dialog>
</template>
