// frontend-vue/src/components/ui/Progress.vue
<script setup lang="ts">
import { ProgressIndicator, ProgressRoot, type ProgressRootProps } from 'reka-ui';
import { cn } from '@/lib/utils';

const props = defineProps<ProgressRootProps & { class?: string; indicatorClass?: string }>();
</script>

<template>
  <ProgressRoot
    v-bind="props"
    :class="cn('relative h-3.5 w-full overflow-hidden rounded-full border-2 border-border bg-muted', props.class)"
  >
    <ProgressIndicator
      :class="cn('h-full w-full flex-1 bg-primary transition-all', props.indicatorClass)"
      :style="{ transform: `translateX(-${100 - (props.modelValue || 0)}%)` }"
    />
  </ProgressRoot>
</template>

// frontend/src/components/ui/progress.tsx
'use client';

import * as React from 'react';
import * as ProgressPrimitive from '@radix-ui/react-progress';
import { cn } from '@/lib/utils';

const Progress = React.forwardRef<
  React.ElementRef<typeof ProgressPrimitive.Root>,
  React.ComponentPropsWithoutRef<typeof ProgressPrimitive.Root> & { indicatorClassName?: string }
>(({ className, value, indicatorClassName, ...props }, ref) => (
  <ProgressPrimitive.Root
    ref={ref}
    className={cn(
      'relative h-3.5 w-full overflow-hidden rounded-full border-2 border-border bg-muted',
      className,
    )}
    {...props}
  >
    <ProgressPrimitive.Indicator
      className={cn('h-full w-full flex-1 bg-primary transition-all', indicatorClassName)}
      style={{ transform: `translateX(-${100 - (value || 0)}%)` }}
    />
  </ProgressPrimitive.Root>
));
Progress.displayName = ProgressPrimitive.Root.displayName;

export { Progress };
