// frontend/src/components/credit-cards/credit-card-form-dialog.tsx
'use client';

import { zodResolver } from '@hookform/resolvers/zod';
import { useForm } from 'react-hook-form';
import { toast } from 'sonner';
import { Button } from '@/components/ui/button';
import {
  Dialog,
  DialogContent,
  DialogFooter,
  DialogHeader,
  DialogTitle,
} from '@/components/ui/dialog';
import { Form, FormControl, FormField, FormItem, FormLabel, FormMessage } from '@/components/ui/form';
import { Input } from '@/components/ui/input';
import { Select, SelectContent, SelectItem, SelectTrigger, SelectValue } from '@/components/ui/select';
import { getApiErrorMessage } from '@/lib/api/client';
import { useCreateCreditCard } from '@/lib/hooks/use-credit-cards';
import { CardBrand } from '@/lib/types';
import { creditCardSchema, type CreditCardFormValues } from '@/lib/validations/credit-card';

export function CreditCardFormDialog({
  householdId,
  open,
  onOpenChange,
}: {
  householdId: string;
  open: boolean;
  onOpenChange: (open: boolean) => void;
}) {
  const createCard = useCreateCreditCard(householdId);
  const form = useForm<CreditCardFormValues>({
    resolver: zodResolver(creditCardSchema),
    defaultValues: { name: '', brand: CardBrand.OTHER, creditLimit: 0, closingDay: 1, dueDay: 10, color: '#8b5cf6' },
  });

  const onSubmit = (values: CreditCardFormValues) => {
    createCard.mutate(values, {
      onSuccess: () => {
        toast.success('Cartão criado');
        form.reset();
        onOpenChange(false);
      },
      onError: (error) => toast.error(getApiErrorMessage(error)),
    });
  };

  return (
    <Dialog open={open} onOpenChange={onOpenChange}>
      <DialogContent>
        <DialogHeader>
          <DialogTitle>Novo cartão de crédito</DialogTitle>
        </DialogHeader>
        <Form {...form}>
          <form onSubmit={form.handleSubmit(onSubmit)} className="space-y-4">
            <FormField
              control={form.control}
              name="name"
              render={({ field }) => (
                <FormItem>
                  <FormLabel>Nome</FormLabel>
                  <FormControl>
                    <Input placeholder="Ex: Nubank Roxinho" {...field} />
                  </FormControl>
                  <FormMessage />
                </FormItem>
              )}
            />
            <FormField
              control={form.control}
              name="brand"
              render={({ field }) => (
                <FormItem>
                  <FormLabel>Bandeira</FormLabel>
                  <Select value={field.value} onValueChange={field.onChange}>
                    <FormControl>
                      <SelectTrigger>
                        <SelectValue />
                      </SelectTrigger>
                    </FormControl>
                    <SelectContent>
                      {Object.values(CardBrand).map((brand) => (
                        <SelectItem key={brand} value={brand} className="capitalize">
                          {brand}
                        </SelectItem>
                      ))}
                    </SelectContent>
                  </Select>
                </FormItem>
              )}
            />
            <FormField
              control={form.control}
              name="creditLimit"
              render={({ field }) => (
                <FormItem>
                  <FormLabel>Limite</FormLabel>
                  <FormControl>
                    <Input type="number" step="0.01" min="0" {...field} />
                  </FormControl>
                  <FormMessage />
                </FormItem>
              )}
            />
            <div className="grid grid-cols-2 gap-4">
              <FormField
                control={form.control}
                name="closingDay"
                render={({ field }) => (
                  <FormItem>
                    <FormLabel>Dia de fechamento</FormLabel>
                    <FormControl>
                      <Input type="number" min="1" max="31" {...field} />
                    </FormControl>
                    <FormMessage />
                  </FormItem>
                )}
              />
              <FormField
                control={form.control}
                name="dueDay"
                render={({ field }) => (
                  <FormItem>
                    <FormLabel>Dia de vencimento</FormLabel>
                    <FormControl>
                      <Input type="number" min="1" max="31" {...field} />
                    </FormControl>
                    <FormMessage />
                  </FormItem>
                )}
              />
            </div>
            <DialogFooter>
              <Button type="submit" disabled={createCard.isPending}>
                {createCard.isPending ? 'Salvando...' : 'Criar cartão'}
              </Button>
            </DialogFooter>
          </form>
        </Form>
      </DialogContent>
    </Dialog>
  );
}

// frontend/src/components/credit-cards/CreditCardFormDialog.vue
<script setup lang="ts">
import { toTypedSchema } from '@vee-validate/zod';
import { useForm } from 'vee-validate';
import { toast } from 'vue-sonner';
import Button from '@/components/ui/Button.vue';
import { Dialog, DialogContent, DialogFooter, DialogHeader, DialogTitle } from '@/components/ui/dialog';
import FormItem from '@/components/ui/FormItem.vue';
import FormMessage from '@/components/ui/FormMessage.vue';
import Input from '@/components/ui/Input.vue';
import Label from '@/components/ui/Label.vue';
import { Select, SelectContent, SelectItem, SelectTrigger, SelectValue } from '@/components/ui/select';
import { getApiErrorMessage } from '@/lib/api/client';
import { useCreateCreditCard } from '@/composables/useCreditCards';
import { CardBrand } from '@/lib/types';
import { creditCardSchema } from '@/lib/validations/credit-card';

const props = defineProps<{ householdId: string }>();
const open = defineModel<boolean>('open', { required: true });

const createCard = useCreateCreditCard(props.householdId);
const { defineField, errors, handleSubmit, resetForm } = useForm({
  validationSchema: toTypedSchema(creditCardSchema),
  initialValues: { name: '', brand: CardBrand.OTHER, creditLimit: 0, closingDay: 1, dueDay: 10, color: '#8b5cf6' },
});

const [name, nameAttrs] = defineField('name');
const [brand, brandAttrs] = defineField('brand');
const [creditLimit, creditLimitAttrs] = defineField('creditLimit');
const [closingDay, closingDayAttrs] = defineField('closingDay');
const [dueDay, dueDayAttrs] = defineField('dueDay');

const onSubmit = handleSubmit((values) => {
  createCard.mutate(values, {
    onSuccess: () => {
      toast.success('Cartão criado');
      resetForm();
      open.value = false;
    },
    onError: (error) => toast.error(getApiErrorMessage(error)),
  });
});
</script>

<template>
  <Dialog v-model:open="open">
    <DialogContent>
      <DialogHeader>
        <DialogTitle>Novo cartão de crédito</DialogTitle>
      </DialogHeader>
      <form class="space-y-4" @submit="onSubmit">
        <FormItem>
          <Label for="name">Nome</Label>
          <Input id="name" v-model="name" v-bind="nameAttrs" placeholder="Ex: Nubank Roxinho" />
          <FormMessage :message="errors.name" />
        </FormItem>
        <FormItem>
          <Label>Bandeira</Label>
          <Select v-model="brand" v-bind="brandAttrs">
            <SelectTrigger>
              <SelectValue />
            </SelectTrigger>
            <SelectContent>
              <SelectItem v-for="cardBrand in Object.values(CardBrand)" :key="cardBrand" :value="cardBrand" class="capitalize">
                {{ cardBrand }}
              </SelectItem>
            </SelectContent>
          </Select>
        </FormItem>
        <FormItem>
          <Label for="creditLimit">Limite</Label>
          <Input id="creditLimit" v-model="creditLimit" v-bind="creditLimitAttrs" type="number" step="0.01" min="0" />
          <FormMessage :message="errors.creditLimit" />
        </FormItem>
        <div class="grid grid-cols-2 gap-4">
          <FormItem>
            <Label for="closingDay">Dia de fechamento</Label>
            <Input id="closingDay" v-model="closingDay" v-bind="closingDayAttrs" type="number" min="1" max="31" />
            <FormMessage :message="errors.closingDay" />
          </FormItem>
          <FormItem>
            <Label for="dueDay">Dia de vencimento</Label>
            <Input id="dueDay" v-model="dueDay" v-bind="dueDayAttrs" type="number" min="1" max="31" />
            <FormMessage :message="errors.dueDay" />
          </FormItem>
        </div>
        <DialogFooter>
          <Button type="submit" :disabled="createCard.isPending.value">
            {{ createCard.isPending.value ? 'Salvando...' : 'Criar cartão' }}
          </Button>
        </DialogFooter>
      </form>
    </DialogContent>
  </Dialog>
</template>
